services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nutrition_service
        volumes:
            - ./:/nutrition-service
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${POSTGRES_DB}
            - DB_USERNAME=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - APP_DEBUG=true
        depends_on:
            db:
                condition: service_healthy
        networks:
            - nutrition-network

    web:
        image: nginx:alpine
        container_name: nutrition_service_web
        ports:
            - "8080:80"
        volumes:
            - ./:/nutrition-service
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - nutrition-network

    db:
        image: postgres:16-alpine
        container_name: nutrition_service_db
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - nutrition-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    db_data:

networks:
    nutrition-network:
        driver: bridge
